version: '3.8'

services:
  nbn-oidc-provider:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    environment:
      - NODE_ENV=production
      # You can override config values with environment variables if needed
      # - DATABASE_URL=mysql://user:password@host:port/database
      # - CACHE_URL=redis://host:port/
    restart: unless-stopped