version: '3.8'

services:
  nbn-oidc-provider:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - ./data:/app/data
    environment:
      - NODE_ENV=production
      # Database configuration - uncomment and modify for your environment
      # - DATABASE_URL=mysql://user:password@host:port/database
      # - CACHE_URL=redis://host:port/
    restart: unless-stopped
